#!/usr/bin/env python3
"""Write rom_hack_docs/dex_order.md - the dex in the order the game shows it.

This is a review aid for the ordering itself: it lists the 132 dex slots the
game actually builds (not the 135 rows of regional_dex.md), and against each one
puts the facts you need to judge whether it sits in the right place - what the
player has to do to get it, whether it's an evolution of the entry above it, and
whether it's legendary/mythical/paradox.

    python3 dev_scripts/dex_order_doc.py

The Review section at the end flags orderings that usually indicate a mistake:
families split apart, special Pokemon stranded mid-list, entries with no way to
obtain them. A flag is a prompt to look, not proof of a bug.
"""

import re, os, sys, glob, collections

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from regional_dex_gen import resolve, species_constants
from obtainable import collect
from dex_worksheet import read_dex, candidates, field, resolve as resolve_expr

OUT = 'rom_hack_docs/dex_order.md'
INFO = 'src/data/pokemon/species_info'


def species_values():
    """SPECIES_X -> numeric id, following the alias defines."""
    raw = dict(re.findall(r'#define\s+(SPECIES_[A-Z0-9_]+)\s+(\S+)',
                          open('include/constants/species.h').read()))
    def val(n):
        v = raw.get(n)
        return None if v is None else (int(v) if v.isdigit() else val(v))
    return {n: val(n) for n in raw}


def species_blocks():
    """SPECIES_X -> the text of its species_info entry."""
    out = {}
    for f in glob.glob(os.path.join(INFO, '*.h')):
        src = open(f, encoding='utf-8').read()
        for m in re.finditer(r'\n    \[(SPECIES_[A-Z0-9_]+)\]\s*=\s*\{', src):
            depth, i = 1, m.end()
            while depth and i < len(src):
                depth += (src[i] == '{') - (src[i] == '}')
                i += 1
            out[m.group(1)] = src[m.end():i]
    return out


def type_macros():
    """Some families put their types behind a #define, e.g. ROTOM_FAMILY_TYPES."""
    out = {}
    for f in glob.glob(os.path.join(INFO, '*.h')):
        for m in re.finditer(r'#define\s+([A-Z_0-9]+)\s*(\{[^}]*\})',
                             open(f, encoding='utf-8').read()):
            out[m.group(1)] = m.group(2)
    return out


TYPE_MACROS = None


def type_str(block):
    t = field(block, 'types')
    if not t:
        return '?'
    if 'TYPE_' not in t:
        t = TYPE_MACROS.get(t.strip(), t)
    got = re.findall(r'TYPE_([A-Z_]+)', t)
    if not got:
        return '?'
    got = [x.title().replace('_', ' ') for x in got]
    return got[0] if len(got) < 2 or got[0] == got[1] else '/'.join(got[:2])


def bst(block):
    keys = ('baseHP', 'baseAttack', 'baseDefense', 'baseSpAttack', 'baseSpDefense', 'baseSpeed')
    vals = [resolve_expr(field(block, k)) for k in keys]
    return sum(int(v) for v in vals if v and str(v).isdigit())


def evo_targets(block):
    return re.findall(r'SPECIES_[A-Z0-9_]+', field(block, 'evolutions') or '')


def main():
    global TYPE_MACROS
    TYPE_MACROS = type_macros()
    slots = resolve()                                   # [(NATIONAL_DEX_X, [display names])]
    consts, vals, blocks = species_constants(), species_values(), species_blocks()
    rows_by_name = {name: (num, note) for num, name, note in
                    [(n, nm, nt) for n, nm, nt in read_dex()]}

    # Resolve each display name back to its own species, so forms keep their own data.
    def species_of(name):
        return next((c for c in candidates(name) if c in consts), None)

    sources = collect()
    entries, in_dex = [], set()
    for names in (n for _, n in slots):
        for n in names:
            in_dex.add(vals.get(species_of(n)))

    for slot, (key, names) in enumerate(slots, start=1):
        forms = []
        for name in names:
            sp = species_of(name)
            block = blocks.get(sp, '')
            val = vals.get(sp)
            how = sorted(sources.get(sp, ()))
            # This expansion has no isLegendary flag; the perfect-IV count is
            # what marks a legendary, and paradox mons carry their own count.
            iv = field(block, 'perfectIVCount') or ''
            tags = ['legendary'] if 'LEGENDARY' in iv else []
            forms.append(dict(name=name, row=rows_by_name.get(name, ('?', ''))[0],
                              type=type_str(block), bst=bst(block), tags=tags,
                              how=how or ['none found'],
                              note=rows_by_name.get(name, ('', ''))[1]))
        entries.append(dict(slot=slot, key=key, forms=forms))

    lines = [
        '# Dex Order',
        '',
        'Generated by `dev_scripts/dex_order_doc.py` - do not hand-edit; change',
        '`regional_dex.md` and regenerate. This is the order the game shows, so it lists',
        f'the {len(entries)} dex slots rather than the {sum(len(e["forms"]) for e in entries)} rows of the source list: regional forms',
        'share their base species\' slot. "Row" is the number in `regional_dex.md`.',
        '',
        '| Slot | Row | Pokemon | Type | BST | Special | How you get it |',
        '|-----:|----:|---------|------|----:|---------|----------------|',
    ]
    for e in entries:
        for i, f in enumerate(e['forms']):
            lines.append('| %s | %s | %s | %s | %s | %s | %s |' % (
                e['slot'] if i == 0 else '"',
                f['row'], f['name'], f['type'], f['bst'],
                ', '.join(f['tags']) or '-', '; '.join(f['how'])))

    # ---- Review flags -------------------------------------------------------
    flags = []
    special = [e for e in entries if any(f['tags'] for f in e['forms'])]
    if special:
        tail = len(entries) - len(special)
        for e in special:
            where = 'end of the dex' if e['slot'] > tail else f'mid-list (slot {e["slot"]} of {len(entries)})'
            flags.append('- %s (%s) is %s' % (
                e['forms'][0]['name'], ', '.join(e['forms'][0]['tags']), where))

    # Evolution families should occupy one unbroken run of slots. Branches like
    # Poliwrath/Politoed are fine; a member stranded elsewhere in the dex is not.
    slot_of = {}
    for e in entries:
        for f in e['forms']:
            slot_of[species_of(f['name'])] = e['slot']
    family = {sp: sp for sp in slot_of}
    def root(x):
        while family[x] != x:
            x = family[x]
        return x
    for sp in slot_of:
        for target in evo_targets(blocks.get(sp, '')):
            if target in slot_of:
                family[root(target)] = root(sp)
    by_slot = collections.defaultdict(list)
    for sp, s in slot_of.items():
        by_slot[s].append(sp)
    for shared in by_slot.values():          # Meowth's forms share slot 69
        for sp in shared[1:]:
            family[root(sp)] = root(shared[0])
    grouped = collections.defaultdict(set)
    for sp in slot_of:
        grouped[root(sp)].add(slot_of[sp])
    for r, members in sorted(grouped.items(), key=lambda kv: min(kv[1])):
        span = sorted(members)
        if len(span) > 1 and span != list(range(span[0], span[0] + len(span))):
            names = sorted((slot_of[sp], sp.replace('SPECIES_', '').title())
                           for sp in slot_of if root(sp) == r)
            flags.append('- %s family is split across slots %s' % (
                names[0][1], ', '.join(str(n) for n, _ in names)))

    for e in entries:
        for f in e['forms']:
            if f['how'] == ['none found']:
                flags.append('- %s has no wild encounter, gift, static or evolution into it' % f['name'])

    lines += ['', '## Review', '',
              'Automatic flags - each is a prompt to look, not proof of a problem.', '']
    seen = set()
    flags = [f for f in flags if not (f in seen or seen.add(f))]
    lines += flags or ['- nothing flagged']
    lines += ['',
              '## Order at a glance', '',
              '- Slots 1-%d: starters (%s)' % (
                  9, ', '.join(f['name'] for e in entries[:9] for f in e['forms'])),
              '- Slot %d is the last entry: %s' % (len(entries), entries[-1]['forms'][0]['name']),
              '- Legendary/mythical/paradox entries: %s' % (
                  ', '.join('%s (slot %d)' % (e['forms'][0]['name'], e['slot'])
                            for e in special) or 'none'),
              '']

    open(OUT, 'w', encoding='utf-8').write('\n'.join(lines) + '\n')
    print(f'wrote {OUT}: {len(entries)} slots, {len(flags)} review flags')


if __name__ == '__main__':
    sys.exit(main())
