#!/usr/bin/env python3
"""Rewrite the in-game regional dex from rom_hack_docs/regional_dex.md.

The dex list is the source of truth for what the player can catch; this script
pushes it into the two places the game reads a regional dex from:

    include/constants/pokedex.h    enum HoennDexOrder + HOENN_DEX_COUNT
    src/pokemon.c                  sHoennToNationalOrder

    python3 dev_scripts/regional_dex_gen.py           rewrite both
    python3 dev_scripts/regional_dex_gen.py --check   report drift, touch nothing

Both tables are keyed by national dex number, which has no per-form entries, so
regional forms share a slot with their base species - Meowth's three forms are
one dex entry, as are Persian's two. The list's 135 rows collapse to 132 slots.

Save compatibility: dexSeen/dexCaught are indexed by national dex number and
sized by POKEMON_SLOTS_NUMBER, neither of which this script touches. Existing
saves keep every seen/caught flag; only the order they're listed in changes.
"""

import re, sys, os

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from dex_worksheet import read_dex, candidates

DEX_H = 'include/constants/pokedex.h'
POKEMON_C = 'src/pokemon.c'
BANNER = '// Generated by dev_scripts/regional_dex_gen.py from rom_hack_docs/regional_dex.md.'


def species_constants():
    return set(re.findall(r'SPECIES_[A-Z0-9_]+', open('include/constants/species.h').read()))


def national_nums():
    """{SPECIES_X: NATIONAL_DEX_Y} straight out of the species info tables."""
    out = {}
    for root, _, files in os.walk('src/data/pokemon/species_info'):
        for f in files:
            if not f.endswith('.h'):
                continue
            src = open(os.path.join(root, f), encoding='utf-8').read()
            for m in re.finditer(r'\[(SPECIES_[A-Z0-9_]+)\]\s*=\s*\{', src):
                tail = src[m.end():m.end() + 4000]
                nat = re.search(r'\.natDexNum\s*=\s*(NATIONAL_DEX_[A-Z0-9_]+)', tail)
                if nat:
                    out[m.group(1)] = nat.group(1)
    return out


def resolve():
    """The dex list as [(national dex constant, display names sharing it)], in order."""
    consts, nat = species_constants(), national_nums()
    slots, seen = [], {}
    for num, name, _ in read_dex():
        species = next((c for c in candidates(name) if c in consts), None)
        if species is None:
            sys.exit(f'{name} (#{num}) does not resolve to a species constant')
        if species not in nat:
            sys.exit(f'{species} (#{num}) has no .natDexNum in species_info')
        key = nat[species]
        if key in seen:
            seen[key].append(name)          # a regional form joining its base species
        else:
            seen[key] = [name]
            slots.append(key)
    return [(k, seen[k]) for k in slots]


def build_enum(slots):
    lines = ['enum HoennDexOrder', '{', '    HOENN_DEX_NONE,']
    for key, names in slots:
        entry = '    ' + key.replace('NATIONAL_DEX_', 'HOENN_DEX_') + ','
        if len(names) > 1:
            entry += '   // ' + ', '.join(names)
        lines.append(entry)
    lines.append('};')
    return '\n'.join(lines)


def build_table(slots):
    lines = ['static const enum NationalDexOrder sHoennToNationalOrder[HOENN_DEX_COUNT - 1] =', '{']
    for key, _ in slots:
        lines.append('    HOENN_TO_NATIONAL(%s),' % key.replace('NATIONAL_DEX_', ''))
    lines.append('};')
    return '\n'.join(lines)


def splice(path, pattern, replacement):
    """Swap the one region matching `pattern`; returns (text, changed)."""
    text = open(path, encoding='utf-8').read()
    m = re.search(pattern, text, re.S)
    if not m:
        sys.exit(f'could not find the generated region in {path}')
    return text[:m.start()] + replacement + text[m.end():], m.group(0) != replacement


def main():
    check = '--check' in sys.argv
    slots = resolve()
    last = slots[-1][0].replace('NATIONAL_DEX_', 'HOENN_DEX_')
    edits = []

    body, changed = splice(
        DEX_H, r'enum HoennDexOrder\n\{.*?\n\};',
        BANNER + '\n' + build_enum(slots))
    body2 = re.sub(r'#define HOENN_DEX_COUNT \(HOENN_DEX_[A-Z0-9_]+ \+ 1\)',
                   f'#define HOENN_DEX_COUNT ({last} + 1)', body)
    # The banner ends up above the enum; drop any copy left from a previous run.
    body2 = body2.replace(BANNER + '\n' + BANNER + '\n', BANNER + '\n')
    edits.append((DEX_H, body2, changed or body2 != body))

    body, changed = splice(
        POKEMON_C, r'static const enum NationalDexOrder sHoennToNationalOrder\[HOENN_DEX_COUNT - 1\] =\n\{.*?\n\};',
        BANNER + '\n' + build_table(slots))
    body = body.replace(BANNER + '\n' + BANNER + '\n', BANNER + '\n')
    edits.append((POKEMON_C, body, changed))

    stale = [p for p, new, ch in edits if open(p, encoding='utf-8').read() != new]
    rows = sum(len(n) for _, n in slots)
    print(f'{rows} dex rows -> {len(slots)} dex slots (HOENN_DEX_COUNT = {len(slots) + 1})')
    for key, names in slots:
        if len(names) > 1:
            print('  shared slot:', key, '=', ', '.join(names))

    if check:
        print('up to date' if not stale else 'out of date: ' + ', '.join(stale))
        return 1 if stale else 0
    for path, new, _ in edits:
        open(path, 'w', encoding='utf-8').write(new)
    print('wrote ' + ', '.join(p for p, _, _ in edits))
    return 0


if __name__ == '__main__':
    sys.exit(main())
